# React Native 0.82 compatible Podfile

platform :ios, '16.0'  # ← updated

require_relative '../node_modules/react-native/scripts/react_native_pods'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'CoachiatryApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true, # enable Hermes
    :fabric_enabled => false, # disable Fabric unless you're using it
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Add RNWorklets manually (for Reanimated 4.x)
pod 'RNWorklets', :path => '../node_modules/react-native-worklets', :modular_headers => true


  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
