# React Native 0.82 compatible Podfile
platform :ios, '16.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

prepare_react_native_project!

use_frameworks! :linkage => :static # static linking avoids further conflicts
$RNFirebaseAsStaticFramework = true

target 'CoachiatryApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
