# React Native 0.82 compatible Podfile
platform :ios, '16.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

prepare_react_native_project!

use_frameworks! :linkage => :static # static linking avoids further conflicts
$RNFirebaseAsStaticFramework = true

target 'CoachiatryApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Fix fmt consteval errors with Xcode 26+ / newer Clang
    fmt_base = File.join(__dir__, 'Pods', 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base)
      content = File.read(fmt_base)
      unless content.include?('force disable consteval')
        content.sub!(
          /\/\/ Detect consteval.*?#define FMT_USE_CONSTEVAL 0\n#endif/m,
          "// Detect consteval, C++20 constexpr extensions and std::is_constant_evaluated.\n// Patched: force disable consteval for Xcode 26+ compatibility\n#define FMT_USE_CONSTEVAL 0"
        )
        File.write(fmt_base, content)
      end
    end
  end
end
