export const theme = {
  colors: {
    white: '#FFFFFF',
    black: '#000',
    background: '#FFF',
    secondary: '#F9F9F9',
    primary: '#0E1734',
    darkGray: '#ECECED',
    gray: {
      50: '#f9fafb',
      100: '#f3f4f6',
      200: '#e5e7eb',
      300: '#d1d5db',
      400: '#9ca3af',
      500: '#6b7280',
      600: '#4b5563',
      700: '#374151',
      800: '#1f2937',
      900: '#111827',
      950: '#030712',
    },
  },
  fonts: {
    archivo: {
      thin: 'Archivo-Thin',
      thinItalic: 'Archivo-ThinItalic',
      extraLight: 'Archivo-ExtraLight',
      extraLightItalic: 'Archivo-ExtraLightItalic',
      light: 'Archivo-Light',
      lightItalic: 'Archivo-LightItalic',
      regular: 'Archivo-Regular',
      italic: 'Archivo-Italic',
      medium: 'Archivo-Medium',
      mediumItalic: 'Archivo-MediumItalic',
      semiBold: 'Archivo-SemiBold',
      semiBoldItalic: 'Archivo-SemiBoldItalic',
      bold: 'Archivo-Bold',
      boldItalic: 'Archivo-BoldItalic',
      extraBold: 'Archivo-ExtraBold',
      extraBoldItalic: 'Archivo-ExtraBoldItalic',
      black: 'Archivo-Black',
      blackItalic: 'Archivo-BlackItalic',
    },
    lato: {
      thin: 'Lato-Thin',
      thinItalic: 'Lato-ThinItalic',
      light: 'Lato-Light',
      lightItalic: 'Lato-LightItalic',
      regular: 'Lato-Regular',
      italic: 'Lato-Italic',
      bold: 'Lato-Bold',
      boldItalic: 'Lato-BoldItalic',
      black: 'Lato-Black',
      blackItalic: 'Lato-BlackItalic',
    },
  },
};
